{% set name = "flowviz" %}
{% set version = "0.1" %}
{% set user = "marximus" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # option 1
  #path: ../
  # option 2
  #git_url: https://github.com/marximus/flowviz.git
  #git_rev: master
  # option 3
  fn: {{ name }}-master.tar.gz
  url: https://api.github.com/repos/{{ user }}/{{ name }}/tarball/master

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib
    - ffmpeg
    - imageio

test:
  imports:
    - flowviz

about:
  home: https://github.com/marximus/flowviz
  license: MIT
  license_file: LICENSE
  summary: Python library for visualization of flow (vector fields)
